// get news
export const GET_NEWS = 'GET_NEWS'

// user's action
export const LOG_IN = 'LOGIN'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const USER_START = 'USER_START'
export const USER_END = 'USER_END'
export const CHECK_LOGIN = 'STAY_LOGIN'
export const CHECK_LOGIN_START = 'CHECK_LOGIN_START'
export const CHECK_LOGIN_END = 'CHECK_LOGIN_END'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const EDIT_PASSWORD_ERROR = 'EDIT_PASSWORD_ERROR'
export const EDIT_PASSWORD_SUCCESS = 'EDIT_PASSWORD_SUCCESS'

// REGISTER
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_END = 'REGISTER_END'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_VEHICLE_SUCCESS = 'REGISTER_VEHICLE_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_VEHICLE_ERROR = 'REGISTER_VEHICLE_ERROR'
export const SENT_OTP_SUCCESS = 'SENT_OTP_SUCCESS'
export const SENT_OTP_ERROR = 'SENT_OTP_ERROR'
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS'
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR'

// wallet
export const GET_SALDO = 'GET_SALDO'

// vehicle
export const GET_VEHICLE = 'GET_VEHICLE'
export const GET_CAR_BRAND = 'GET_CAR_BRAND'
export const GET_ALL_CAR_TYPE = 'GET_ALL_CAR_TYPE'
export const GET_CAR_TYPE = 'GET_CAR_TYPE'
export const GET_MOTOR_BRAND = 'GET_MOTOR_BRAND'
export const GET_MOTOR_TYPE = 'GET_MOTOR_TYPE'
export const GET_VEHICLE_ERROR = 'GET_VEHICLE_ERROR'
export const EDIT_VEHICLE_START = 'EDIT_VEHICLE_START'
export const EDIT_VEHICLE_END = 'EDIT_VEHICLE_END'